export const Classes = {
  classes: ['fighter', 'knight', 'gladiator', 'cleric', 'holyknight', 'guardian', 'mage', 'wizard', 'warlock', 'archer', 'ranger', 'sharpshooter', 'trickster', 'reaper', 'spectre', 'crusader', 'templar'],
  classesValues: [
    {value: 'fighter' , label: 'Fighter'},
    {value: 'knight' , label: 'Knight'},
    {value: 'gladiator' , label: 'Gladiator'},
    {value: 'cleric' , label: 'Cleric'},
    {value: 'holyknight' , label: 'HolyKnight'},
    {value: 'guardian' , label: 'Guardian'},
    {value: 'mage' , label: 'Mage'},
    {value: 'wizard' , label: 'Wizard'},
    {value: 'warlock' , label: 'Warlock'},
    {value: 'archer' , label: 'Archer'},
    {value: 'ranger' , label: 'Ranger'},
    {value: 'sharpshooter' , label: 'Sharpshooter'},
    {value: 'trickster' , label: 'Trickster'},
    {value: 'reaper' , label: 'Reaper'},
    {value: 'spectre' , label: 'Spectre'},
    {value: 'crusader' , label: 'Crusader'},
    {value: 'templar' , label: 'Templar'}
  ],
  allowedClasses: {
    fighter: ['fighter', 'all'],
    knight: ['fighter', 'knight', 'fighter and cleric', 'gladiator and knight', 'all'],
    gladiator: ['fighter', 'gladiator', 'fighter and cleric', 'gladiator and knight', 'all'],
    cleric: ['cleric', 'all'],
    holyknight: ['cleric', 'holyknight', 'fighter and cleric', 'guardian and holyknight', 'all'],
    guardian: ['cleric', 'guardian', 'fighter and cleric', 'guardian and holyknight', 'all'],
    mage: ['mage', 'all'],
    wizard: ['mage', 'wizard', 'all'],
    warlock: ['mage', 'warlock', 'all'],
    archer: ['archer', 'all'],
    ranger: ['archer', 'ranger', 'all'],
    sharpshooter: ['archer', 'sharpshooter', 'all'],
    trickster: ['trickster', 'all'],
    reaper: ['trickster', 'reaper', 'all'],
    spectre: ['trickster', 'spectre', 'all'],
    crusader: ['crusader', 'all'],
    templar: ['crusader', 'templar', 'all'],
  }
 };